# Rutuja More

apiVersion: v1
kind: Service
metadata:
  name: swe645-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: swe645
